### ISSUE TITLE
R version

### ISSUE THREAD

**Issue by mamereu** [Robinlovelace/geocompr#191]
`devtools::install_github("robinlovelace/geocompr")
.............
Installation` failed: Command failed (1)
> install.packages( 'USAboundariesData')
Warning in install.packages :
  package ‘USAboundariesData’ is not available (for R version 3.4.4)``
Which version of R is needed ?

**Comment by Robinlovelace** [comment]
Thanks for raising this issue. I think it's because the **USAboundariesData** has been added to the DESCRIPTION in https://github.com/Robinlovelace/geocompr/commit/1c6c853686390c002aa782e92af468729db73c7e but the package is not on CRAN. My suggested solution: remove the package as a dependency for the book to avoid people having to install 'the kitchen sink' and only run the code that uses the **USAboundariesData** when we rebuild the README.
