### ISSUE TITLE
Confusing paragraph in 4.2.3 Spatial joining

### ISSUE THREAD

**Issue by cbird999** [Robinlovelace/geocompr#252]
In the paragraph below, the authors write the opposite of the results of the operation:

`st_join(random_points, world["name_long"])
`

We actually added features to the point layer from the polygon layer. Also, we did not choose cities - the points were chosen at random. The text seems to belong to a different version of the book. 

'In the example above, we have added features of a point layer to a polygon layer but there might be multiple point matches per polygon. Had we chosen to select the four (instead of three) most populous cities in the world, two of them would have belonged to China (Shanghai and Beijing, give it a try yourself). In such a case st_join() simply adds a new row. In our example we would have ended up with two polygons representing China.'

**Comment by jannes-m** [comment]
Thanks for spotting. You are right there is something off. The paragraph you mention belongs to a previous version of the `st_join` example. Will take care of this.

**Comment by jannes-m** [comment]
solved through aec45c9. @Robinlovelace pls have a look if you are happy with this.

**Comment by Robinlovelace** [comment]
Thanks for pointing-out the issue in the text @cbird999 and for the quick-fire fix @jannes-m. Yes it referred to an old version of the code which I forgot to remove so I'm very grateful that you spotted that. Any further issues you find, please let us know!

The text hasn't updated yet because Travis seems to be failing at the moment but check back here in a day or so and it should be sorted: https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining

In summary, 👍 🚿 🚀 !

**Comment by cbird999** [comment]
Thanks for the quick reply. I found a few other small problems that would
probably trick a beginner. I will post them to github when I get the
chance. BTW - I love the book. I've been doing GIS for long time now, but
I'm learning a lot about R geocomp, esp. the sf library, which I didn't
even know existed!
