### ISSUE TITLE
book rendering not completing

### ISSUE THREAD

**Issue by jldupouey** [Robinlovelace/geocompr#276]
I try to locally render the book. The command:

> bookdown::render_book("index.Rmd")

ends on the following error:

Quitting from lines 500-508 (14-eco.Rmd) 
Error in `[.data.frame`(data, , forest$independent.variable.names, drop = FALSE) : 
  undefined columns selected
Calls: local ... predict -> predict.ranger.forest -> [ -> [.data.frame

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 14-eco.Rmd

I have uptaded all libraries and R core to the last version available, on my Windows 10 system. All previous packages installations worked fine.

Thank you in advance for your help,

**Comment by jannes-m** [comment]
Not really sure why you need this since this only creates the online version of the book which you can easily access via https://geocompr.robinlovelace.net/. 
In any case, I have just rendered the book using my Windows 10 virtual machine, all worked fine. Have you run `devtools::install_deps()` before rendering?

**Comment by Robinlovelace** [comment]
Closing for now as it seems to be working on other computers. Let us know how you get on @jldupouey, thanks for reporting and please let us know if you discover any other issues with the book's code or text.
