### ISSUE TITLE
replace `library(tidyverse)` with specific packages.

### ISSUE THREAD

**Issue by barryrowlingson** [Robinlovelace/geocompr#331]
Controversial maybe, but you should avoid `library(tidyverse)` in user code. Its a great way of pulling in multiple packages that you have no control over, with the potential for function name clashes happening further down the line in packages that you don't even need in your code.

Replace with the specific packages used in the code - I had a quick look at one section and it only seemed to use `dplyr`. This increases clarity and focus, as well as keeping dependencies light.

**Comment by Robinlovelace** [comment]
Yes good point and will help users know exactly what they are using. It's important to know that `filter()` is a **dplyr** function and not a 'tidyverse function'. Limited time to implement this change this week though.

Thanks loads for the feedback. Any more suggestions in these final weeks before the proofs come back from copy-editing: welcome.

**Comment by Robinlovelace** [comment]
Heads-up @barryrowlingson the commit above implements this for all chapter headings. I had to attach **purrr** in one place but otherwise you're right: the only package needed for all other chapters was **dplyr** it seems, so unnecessary to import the metaphorical kitchen sink! Feedback welcome. If travis passes and you're happy with this I think that's job done and a clear improvement from a namespace perspective.

**Comment by Robinlovelace** [comment]
Hey @barryrowlingson does this fix it for you? https://github.com/Robinlovelace/geocompr/pull/333 :pray: Travis works this time - if only we'd started this way!

**Comment by barryrowlingson** [comment]
Looks good!

**Comment by Robinlovelace** [comment]
Thanks for the feedback. Any other issues you spot with your beady :eyes: please raise them before this book :rocket:

**Comment by Robinlovelace** [comment]
Thanks for the feedback. Any other issues you spot with your beady :eyes:  please raise them before this book :rocket:
