### ISSUE TITLE
Redundant code in 4.2.3?

### ISSUE THREAD

**Issue by Henrik-P** [Robinlovelace/geocompr#352]
In [4.2.3 Spatial joining](https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining), two lines of code seem redundant:

`world$name_long = as.character(world$name_long)`

"name_long" is already a character vector in the original "world" data.

`world_random = world[random_points, ]`

"world_random" doesn't seem to be used in the chapter.

**Comment by Robinlovelace** [comment]
Thanks for pointing out these issues. 

Regarding the 1st, I assigned it to a character because in an old version of the world dataset it was a factor. But you correctly point out that this is no longer the case:

``` r
class(spData::world$name_long)
#> [1] "character"
```

<sup>Created on 2018-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I've removed the `as.character()` line, fixing the first part of the issue (see commit below for details of the fix).

`world_random` was used in the chapter, but not explicitly (it creates the top right panel of the figure). I've now rewritten the section so that the purpose of doing the spatial subsetting is made clear. It also now shows the link between spatial subsetting and spatial joining.

Please take a look at the updated results at https://geocompr.robinlovelace.net/spatial-operations.html#spatial-joining and let us know if you find any other issues. The feedback is greatly appreciated!

**Comment by Robinlovelace** [comment]
https://github.com/Robinlovelace/geocompr/commit/535fe58232b9db27c72e3ab6cd530db89340d11d
