### ISSUE TITLE
current master not building

### ISSUE THREAD

**Issue by etabeta78** [Robinlovelace/geocompr#366]
In Chapter 13 (13-location.Rmd) markdown source searches for a `locality` column in metro_names (from spDataLarge) which is not there in the data available in current spDataLarge master tree.

I can fix the problem by loading an older rda from spDataLarge repository, but I guessed you could have been interested about this change in the data structure for its consequences here.

**Comment by jannes-m** [comment]
Could you please point to the specific passage in the text? Because I cannot find one instance in `13-location.Rmd` where we are looking for a `locality`-column. I remember that the `locality` column was an output of GoogleMaps geocoding API. But we now use the Photon API through **revgeo** for the geocoding.

**Comment by etabeta78** [comment]
Sorry for the false alarm... It was my fault.
I had on a different folder of my machine an older master tree from August 2018 which used that column :-(
yesterday, despite downloading the latest master, I ended up building the older master tree (which probably was building with last August spDataLarge)

**Comment by Robinlovelace** [comment]
Thanks for raising the issue @etabeta78 and now worries about false alarms. If you spot any other issues, please let us know.
