### ISSUE TITLE
Section on web services and OGC standards

### ISSUE THREAD

**Issue by cvitolo** [Robinlovelace/geocompr#39]
OGC standards such as WMS/WFS/WCS/... are becoming very common (hurray!) and many data providers serve layers via web services. 

A section on how to assemble a typical request and visualise the response would be fantastic!

**Comment by Robinlovelace** [comment]
Hi @cvitolo it's over a year since you raised this idea and a lot has changed. We've got a complete book! Could you take a look and suggest where you think such a section would work best? I'm guessing in chapter 7 of data I/O, just before this section: https://geocompr.robinlovelace.net/read-write.html#geographic-data-packages

Thoughts? Agreed getting data from standard web services is a very useful skill and I don't think we've covered it yet. We have a window of opportunity before it gets sent to copy-editing in a few weeks!

**Comment by Robinlovelace** [comment]
Apologies for not acting on this sooner btw.

**Comment by cvitolo** [comment]
Great work!

I agree, accessing data via web service would suite section 7.2 

Many thanks for taking my suggestion into account.

**Comment by Robinlovelace** [comment]
Fantastic. Another question: do you have any example data/resources/code showing how to import data from web services? Thinking a minimal reproducible example here would be most useful.

**Comment by Robinlovelace** [comment]
Downloading data from a WFS such as http://www.bgs.ac.uk/data/services/wfs.html would be very useful. Any code showing how to do that: very much appreciated, e.g. from: http://ogc.bgs.ac.uk/digmap625k_gsml32_cgi_gs/wfs?service=WFS&request=GetCapabilities&AcceptVersions=2.0.0&

**Comment by Robinlovelace** [comment]
@cvitolo please take a look here: https://github.com/Robinlovelace/geocompr/pull/322

Is that the kind of content you were thinking? I'm new to OWS in R so certainly room for improvement!

**Comment by cvitolo** [comment]
Sorry for the late reply @robinlovelace, was traveling during the past week.

In terms of OGC standards, I would mention the sos4R (An R client for the OGC Sensor Observation Service, the are plenty of examples in the manual).

There is a basic example of how to list WCS layers here: https://github.com/OpenDataHack/data_service_catalogue/blob/master/ecmwf_web_coverage_service.ipynb

Some examples of how to visualise WMS using leaflet: 
- https://rstudio.github.io/leaflet/basemaps.html
- https://gis.stackexchange.com/questions/230193/wms-in-leaflet-r
- https://gist.github.com/ateucher/297a0ddc2c78306a518c4fe2063d4f11

**Comment by Robinlovelace** [comment]
Many thanks Claudia, this is very, very useful. i'll try to get something in the master branch, just in time for it being submitted for production!

**Comment by Robinlovelace** [comment]
Seems sos4R is no longer on CRAN. Any ideas why? Cc @edzer - apologies for nudge Edzer but as you'll see from #322 I'm writing a small section on web services but this is not my area of expertise. Would you recommend pointing people to **sos4R** and do you have any suggested resources beyond those kindly provided by Claudia above? Thanks!

**Comment by edzer** [comment]
@nuest

**Comment by eblondel** [comment]
@Robinlovelace may I suggest you look at the revision of the CRAN spatial task view i've sent some days ago? where more emphasis was given on standards: on formats first  (https://github.com/r-spatial/task_views/blob/master/ctv/Spatial.ctv#L149) with stronger referencing of ``sf`` package, and services then (https://github.com/r-spatial/task_views/blob/master/ctv/Spatial.ctv#L211). On services ,distinction could be done between OGC standards and software product - specific services (API Clients). May I suggest also you look into the following packages:
* [geosapi](https://github.com/eblondel/geosapi/wiki) package which offers an interface to the known [GeoServer](http://geoserver.org/) open-source and its web API for management of spatial data (for which I'm in process to contribute to GeoServer official documentation with R code snippets);
* [geonapi](https://github.com/eblondel/geonapi/wiki) package that interfaces the legacy GeoNetwork API for metadata management, maybe in less extent, since similar management may be operated (by preference) through OGC standard and [ows4R](https://github.com/eblondel/ows4R/wiki) CSW R client. All these packages I refer to are published on CRAN.
Hope this helps
