### ISSUE TITLE
Requested clarification in section 3.3.1: raster subsetting

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#401]
_(General note on this and coming issues. Here follows a series of small issues on understandability for the reader, after having read several book chapters. Don't feel overwhelmed, I just splitted the suggestions/concerns into separate issues so that you can keep track more easily. Despite the list of issues I am a huge fan of the book ;-))_

The first paragraph of section 3.3.1 reads as follows:

> Raster subsetting is done with the base R operator `[`, which accepts a variety of inputs:
> 
> - Row-column indexing
> - Cell IDs
> - Coordinates
> - Another raster object

However it appears that subsetting with `[` using _coordinates_ (third bullet) boils down to first converting coordinates into cell IDs. This is somehow confusing, as from this list one would expect a more direct method with `[`. I suggest to omit 'coordinates'. Perhaps it can be added in brackets after cell IDs: '(c.q. derived from XY coordinates)'.

**Comment by jannes-m** [comment]
Mmh, I guess you are right. Originally, we have also shown that one needs to convert coordinates into cellIDs in order to extract the corresponding raster values (see https://github.com/Robinlovelace/geocompr/commit/2f371162ac90db56b6b0580c86460569283ba9f8).
One could also use `extract()` in combination with coordinates. But here, we are specifically talking about `[` subsetting. It would be also better to say another spatial object instead of another raster object. And we should say that using coordinates or another spatial object is already a spatial operation. And I think this was also the reason why we have deleted the conversion from coordinates into cell ids from the code chunk here because this is already a spatial operation. Yes, exactly, in section 4.3.1 we show spatial subsetting using coordinates and `extract()`.
In fact, I like that we explain all `[` options. So I suggest, we don't delete the mentioning of coordinate extraction here but refer instead to the spatial subsetting section. And we do the same for the extraction by means of another raster object and even make this more general by replacing raster object by spatial object. Do you agree?

**Comment by florisvdh** [comment]
Hi @jannes-m , I think I can follow your suggestion to widen up things. Just make sure that the scope of the bullet list remains clear in that case (first sentence): either it is about ways of subsetting with `[`, or it is more than just that.

**Comment by Robinlovelace** [comment]
I should also say that if you have a clear idea of how to improve things @florisvdh Pull Requests are very welcome! But understand you may want clarification/confirmation before submitting. I think the suggestion by @jannes-m is good.

**Comment by florisvdh** [comment]
@Robinlovelace I agree, thanks, but in this case I feel not experienced enough with the possibilities in **raster** to judge about the best solution or the actual wordings (I think that's more or less true for most of my posted issues, but there may be exceptions after some discussion indeed). I just read the book to learn, and I've already learned much from it - thanks a lot!

**Comment by jannes-m** [comment]
closed via aacdcc66571df0c1b65f6d12be7c21a996a3d147
