### ISSUE TITLE
Requested enhancement in section 5.3: geometric operations on raster data

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#405]
This is a comment on the introductory part before section 5.3.1. Rather than introducing the topics that follow, the text focuses on other applications. Of course it does not harm to mention those, but it would read much better if you start with (and focus on) the topics that _are_ treated, just as in 5.2. I think that a large part of this text would fit better in a subsection '5.3.4 More advanced operations', at the end of 5.3.

**Comment by jannes-m** [comment]
Well, I guess this might be a matter of taste. To give some geospatial background (as we do throughout the book and which is also intended because this welcomes readers coming from a RS/GIS background to R, teaches spatial stuff to people coming from R, in short makes this book a text book) I thought it would be a nice idea to define shortly geometric raster operations. That not all of those can or should be done with R, well... I would also refrain from moving it to more advanced operations section since this in fact a paragraph on geometric raster operations. In any case, thanks for the suggestions!
