### ISSUE TITLE
Requested enhancement regarding section 5.3.1: geometric intersections

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#406]
Apart from the mentioning of `intersect()` and `crop()`, this is just a repetition of a part of 4.3.1 (spatial subsetting), where also the functions `mask()` and `overlay()` are demonstrated. I suggest:

- to avoid this redundancy by partially rethinking how to structure the texts on raster operations
- to explain the differences between these four functions, in one place.

**Comment by jannes-m** [comment]
The difference is that in the first case (4.3.1) we are talking about spatial subsetting. In section 5.3.1 we are talking about geometric operations, i.e., the returned object is e.g., a raster object and not just a value. This is an important difference which is why we have distinguished between spatial and geometric operations. Hence, if you would like to restructure the text you have to come up with a more meaningful structure than attribute, spatial and geometry operations on spatial, i.e., vector and raster, data.

**Comment by florisvdh** [comment]
I'll think further about potential solutions and come back, thanks for your point of view!

Anyhow, I find the distinction between attribute, spatial and geometry operations, and the consistent handling for vector and rasters a very strong point of the book.
