### ISSUE TITLE
Requested clarification in section 5.3.3: the raster::resample() function

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#408]
> The process of computing values for new pixel locations is also called resampling. 
In fact, the **raster** package provides a `resample()` function.
It lets you align several raster properties in one go, namely origin, extent and resolution.
By default, it uses the `bilinear`-interpolation.

> ```{r 05-geometry-operations-42}
> # add 2 rows and columns, i.e. change the extent
> dem_agg = extend(dem_agg, 2)
> dem_disagg_2 = resample(dem_agg, dem)
> ```

From the text above the chunk, it is not clear why you start with `dem_agg`, extend it, and use this for resampling. An explanation clarifying more specifically the purpose of the example would possibly allow the reader to better understand the why and how of resampling. Nevertheless, this example does not really focus on the results of `resample()`, e.g. no output is generated and shown, so I think it currently has little added value.

Essentially, the text does not clearly explain what `resample()` does: 'computing values for new pixel locations' and 'align several raster properties' seem rather vague. You should at least clarify the basic purpose: properties of one raster are used to calculate values of another raster which is not necessarily aligned. So I suggest to better explain `resample()`, at least in the text and preferrably also by means of a more elaborated example.

**Comment by jannes-m** [comment]
I see your point when reading only the paragraph on `resample()`. However, when reading also the paragraph on (dis-)aggregation and the previous section on origin and extent, it should be rather clear what changing the origin, the extent and resolution means. Therefore, to avoid duplication, I suggest to reference the corresponding sections in the text. On the other hand, you are right that the `resample()` example might be improved or deleted. I would be happy with deleting instead of extending it, what do you think (also @Robinlovelace & @Nowosad)?

**Comment by Nowosad** [comment]
I would suggest expanding the part about `resample()`. 1) it could be useful in many cases, 2) there is a reference to this function in the next chapter

**Comment by florisvdh** [comment]
I as well rather prefer to have it kept and improved.

**Comment by Nowosad** [comment]
I will work on this for the second edition.
