### ISSUE TITLE
Issue replicating Chapter 5: rmapshaper error

### ISSUE THREAD

**Issue by DarrellCarvalho** [Robinlovelace/geocompr#637]
I run into an error when trying to execute the code for Chapter 5. This is the code that I am running
`pacman::p_load(sf, raster, dplyr, spData, spDataLarge, rmapshaper)`
`# Simplification ----------------------------------------------------------`
`### Simplifying state polygons`
`# take us_states data and project it to EPSG:2163`
`us_states2163 <- st_transform(us_states, 2163)`
`# ms_simplify from rmapshaper`
`us_states2163 <- as.numeric(us_states2163$AREA)`
`us_states_simp2 <- ms_simplify(us_states2163, keep = 0.01, keep_shapes = TRUE)`

It returns the following error:

`Error in UseMethod("ms_simplify") : 
  no applicable method for 'ms_simplify' applied to an object of class "c('double', 'numeric')"`

**Comment by Robinlovelace** [comment]
I can reproduce the error but it's not an error associated with the book.

This is the code in the book:

https://github.com/Robinlovelace/geocompr/blob/f82c343bcfa5e7883bdf4998f1620ebad19219c5/05-geometry-operations.Rmd#L100-L103

The issue is that you assign `us_states2163`, not `us_states2163$AREA`, to be of class numeric. 
This is your code: 

``` r
pacman::p_load(sf, raster, dplyr, spData, spDataLarge, rmapshaper)
# Simplification ----------------------------------------------------------
### Simplifying state polygons
# take us_states data and project it to EPSG:2163
us_states2163 <- st_transform(us_states, 2163)
# ms_simplify from rmapshaper
us_states2163 <- as.numeric(us_states2163$AREA)
us_states_simp2 <- ms_simplify(us_states2163, keep = 0.01, keep_shapes = TRUE)
#> Error in UseMethod("ms_simplify"): no applicable method for 'ms_simplify' applied to an object of class "c('double', 'numeric')"
```

<sup>Created on 2021-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is the working code from the book:

``` r
pacman::p_load(sf, raster, dplyr, spData, spDataLarge, rmapshaper)
us_states2163 = st_transform(us_states, 2163)
us_states2163$AREA = as.numeric(us_states2163$AREA)
us_states_simp2 = rmapshaper::ms_simplify(us_states2163, keep = 0.01,
                                          keep_shapes = TRUE)
```

<sup>Created on 2021-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
