### ISSUE TITLE
polygons / raster intersection

### ISSUE THREAD

**Issue by mtennekes** [Robinlovelace/geocompr#657]
What is the fastest way to do the following task? 

I have a set of disjoint polygons and an empty raster grid. Each polygons belongs to a certain class, e.g. a specific land use category. For each grid tile and each class, what is the fraction of this grid tile that is covered by polygon(s) of this class?
 
Is this already covered in the book? If so, where, and if not, why not? I ask because I have done it before a few years ago, but recall that is was very time consuming. So I'm wondering what the fastest way is considering the recent heap forwards in r-spatial (stars, terra). There are plenty of projects for which this task would be useful.

**Comment by Nowosad** [comment]
@kadyb do you have any benchmarks similar to the above problem?

**Comment by kadyb** [comment]
@Nowosad, unfortunately no.
@mdsumner, could you advise something?

**Comment by mdsumner** [comment]
{exactextractr} fits the bill for partial overlap afaik, but I haven't used. 

In the past I use {fasterize} and {raster} cell functions to classify cells by polygon because raster was hopelessly slow. {terra}::rasterize possibly works as fast now and includes memory management by offloading to file and/or operating in blocks (fasterize does not, also no partial overlap), and includes aggregation. {stars}  has similar to terra

**Comment by edzer** [comment]
`sf::st_interpolate_aw()` has all the components in it for this, but then aggregates the values, area-weighted, to a single raster value. Package `areal` may provide a more granular approach to this. `sf::st_intersection` returns an object with an `idx` attribute which is a 2-column matrix with the origin index in `x` and `y` geometries, for each new geometry.

**Comment by mdsumner** [comment]
Extraction is rasterization plus value query plus possible aggregation, you can exactextractr cellnumbers so you have index and their weights
