### ISSUE TITLE
Chapter 15 failing

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#773]
With this error on my desktop:

```
Quitting from lines 565-566 (15-eco.Rmd) 
Error: The backend of Task 'mongon' has been removed. Set `store_backends` to `TRUE` during model fitting to conserve it.

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 15-eco.Rmd
```

Heads-up @jannes-m

**Comment by jannes-m** [comment]
For the moment, I think the quick-fix is ok, since we don't necessarily need the `AutoTuner()` output.

It seems that this is again a **mlr3**/**knitr** problem. The error only occurs when reading in an `AutoTuner()` result via `readRDS()` during a `knitr()` process. Reading in the same `AutoTuner()` result in the R console works without problems. 

@pat-s any ideas on this or should I open an mlr3 issue? By the way, the same problem occurred when trying to read in a `bechmark()` result when knitting (see https://github.com/Robinlovelace/geocompr/pull/771)

**Comment by pat-s** [comment]
Are you making use of knitr's cache? See https://github.com/mlr-org/mlr3/wiki/FAQ#caching-of-knitrrmarkdown-chunks-does-not-work-with-mlr3.

If so this is an issue related to knitr and R6 - not directly mlr3 related.

If not, there might be additional issues WRT to serialization and R6 objects. We've tackled a lot in 2020 and implemented some internal workarounds and haven't had any complains since then. Also I think we load a lot of .rds objects in the mlr3gallery.
 
A reprex would be great - but AFAIU the process would be

1. create a BMR in mlr3
2. serizalize it
3. load in in an Rmd document via readRDS -> fail?

**Comment by Robinlovelace** [comment]
> Are you making use of knitr's cache?

I don't think so. Many thanks for the suggestions Pat!

**Comment by jannes-m** [comment]
Thank you so much, @pat-s, the `cache.lazy` knitr option solves the problem!
