### ISSUE TITLE
Ch15: ecology minor comments

### ISSUE THREAD

**Issue by Lvulis** [Robinlovelace/geocompr#842]
Hi guys, almost done with the book and really enjoyed it thus far. I did not leave comments on the geomarketing chapter as it seems it is still to be updated (e.g. switch from {raster} to {terra}). 

For the ecology chapter, there are a few things in here, some are stylistic w.r.t prose (which I try to avoid making but couple of things in here drew attention) and code-wise. Making a separate issue from #786 but some overlap. Agree that these are some of the most interesting vegetation belts known to humans :) I figure this will go to @jannes-m? I can make a PR to address some of these if it helps.
- The first mention of the ordination technique (NMDS) under Fig 15.2 seems a little out of place. 
- "Reducing Dimensionality" _For one, relationships are usually non-linear along environmental gradients. That means the presence of a plant usually follows a unimodal relationship along a gradient (e.g., humidity, temperature or salinity) with a peak at the most favorable conditions and declining ends towards the unfavorable conditions._ I would disagree that a relationship being nonlinear implies it is unimodal, but rather that it is nonlinear because of its unimodality.
- "the most moistest" in the next paragraph should be fixed, I would suggest "the wettest"
- As mentioned in #786 `scores()` in the `xy-nmds-code` chunk is returning a 2-list, it seems the first element is what was previously targeted. Would recommend subsetting it explicitly when defining `sc`. 
```R
> plot(y = sc[, 1], x = elev, xlab = "elevation in m", 
+      ylab = "First NMDS axis", cex.lab = 0.8, cex.axis = 0.8)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'plot': incorrect number of dimensions

# FIXED by subsetting the scores output when defining sc. This helps downstream.
sc = vegan::scores(rotnmds, choices = 1:2)$sites
# plotting the first axis against altitude
plot(y = sc[, 1], x = elev, xlab = "elevation in m", 
     ylab = "First NMDS axis", cex.lab = 0.8, cex.axis = 0.8)
```
- There's an empty code chunk above `15-eco-20` that should be removed (L462-464).
- L602 _The predictive mapping clearly reveals distinct..._ figure reference is broken. It isn't clear what figure that entire paragraphs is referring too, is it from Muenchow et al., 2013? That article isn't OA, would be good to replicate it here if possible.
- Should **lomas** be _lomas_ everywhere?
- The interpretable machine learning link in the conclusion (L625) should be: https://mlr3book.mlr-org.com/09-interpretation-iml.html. That bullet point also has 2 sentences and needs a .
- The exercises aren't rendering at all!

**Comment by Robinlovelace** [comment]
Same as my comments on #786 these are important comments but not necessarily a blocker for progress on https://github.com/Robinlovelace/geocompr/milestone/10

**Comment by jannes-m** [comment]
First of all, thanks a lot for taking the time to read and review the chapter, @Lvulis, I greatly appreciate it! Please find my point-by-point reply below.

> The first mention of the ordination technique (NMDS) under Fig 15.2 seems a little out of place.

How would you rewrite it? I just wanted to point out that we need the environmental variables in part also for the NMDS and referring the reader to the corresponding section for more details. 

> "Reducing Dimensionality" For one, relationships are usually non-linear along environmental gradients. That means the presence of a plant usually follows a unimodal relationship along a gradient (e.g., humidity, temperature or salinity) with a peak at the most favorable conditions and declining ends towards the unfavorable conditions. I would disagree that a relationship being nonlinear implies it is unimodal, but rather that it is nonlinear because of its unimodality.

I agree. However, the relationship often depends on the length of the observed gradient. To address your concern, I have slightly rewritten as follows: For one, the presence of a plant often follows a unimodal, i.e. a non-linear, relationship along a gradient (e.g., humidity, temperature or salinity) with a peak at the most favorable conditions and declining ends towards the unfavorable conditions.

> "the most moistest" in the next paragraph should be fixed, I would suggest "the wettest"

I have discussed this before with other reviewers and I would like to stick with "moistest" since the conditions are in fact better described with moist than wet. You have to keep in mind that this is an ecosystem in one of the driest deserts of the world and that plants collect water most of the time by combing out fog.

> As mentioned in
https://github.com/Robinlovelace/geocompr/issues/786 scores() in the xy-nmds-code chunk is returning a 2-list, it seems the first element is what was previously targeted. Would recommend subsetting it explicitly when defining sc.

I have addressed this by using now `scores(rp, choices = 1:2, display = "sites")`. Thanks for noting and providing a solution!

> There's an empty code chunk above 15-eco-20 that should be removed (L462-464).

It seems that has already been addressed.

> L602 The predictive mapping clearly reveals distinct... figure reference is broken. It isn't clear what figure that entire paragraphs is referring too, is it from Muenchow et al., 2013? That article isn't OA, would be good to replicate it here if possible.

This has been fixed, figure is now displayed again. If of interest, the article is available via researchgate.

> Should **lomas** be *lomas*

Certainly! Thanks for noting and changed as proposed. 

> The interpretable machine learning link in the conclusion (L625) should be: https://mlr3book.mlr-org.com/09-interpretation-iml.html. That bullet point also has 2 sentences and needs 

Thanks, link was fixed.

> The exercises aren't rendering at all!

Ok, I still have to look at the exercises.

Once again thanks for reviewing and please feel free to also raise your stylistic concerns!

**Comment by Lvulis** [comment]
Was very happy to read through and learn about lomas and apply **mlr3**, so thank you for putting together this chapter!

> How would you rewrite it? I just wanted to point out that we need the environmental variables in part also for the NMDS and referring the reader to the corresponding section for more details.

Not sure what I was thinking at the time re-reading it seems absolutely fine. 

> I agree. However, the relationship often depends on the length of the observed gradient. To address your concern, I have slightly rewritten as follows: For one, the presence of a plant often follows a unimodal, i.e. a non-linear, relationship along a gradient (e.g., humidity, temperature or salinity) with a peak at the most favorable conditions and declining ends towards the unfavorable conditions.

Got it! The original seemed to switch the causality (the non-linearity implies unimodality other than vice-versa) which was the only thing that stuck out.

> I have discussed this before with other reviewers and I would like to stick with "moistest" since the conditions are in fact better described with moist than wet. You have to keep in mind that this is an ecosystem in one of the driest deserts of the world and that plants collect water most of the time by combing out fog.

Rereading, this was more about the "most" than the wetness vs. moistness: i.e. "most moistest" sounded more awkward than "most moist" or "the moistest" (similar to the driest in the same sentence). 

For everything else looks great and good luck with wrapping up Version 2.

**Comment by jannes-m** [comment]
Thanks a lot!
