### ISSUE TITLE
Reduce size of code chunk in Ecology chapter

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#852]
As shown here:

![image](https://user-images.githubusercontent.com/1825120/186132080-26adb15f-eae4-43c2-a220-9ca3a340a2d1.png)

Should be a small fix. I'm up for giving it a go.

**Comment by jannes-m** [comment]
Leave it to me. I plan to batch process all my issues during my parental leave (until 23.10.).

**Comment by Robinlovelace** [comment]
Amazing, thanks Jannes. When does it start and when's good for an afternoon geocomp mini hack one day? Greetings from me and Jakub in Florence!

**Comment by jannes-m** [comment]
Hey there, 
I plan to start acting on my issues as soon as we are back from our holiday trip, hence after 6. September. 
In the meantime I spend some night shifts on increasing my productivity and how to remember and link reliably knowledge and ideas. The Zettelkasten (slip box) is especially intriguing for academics. If you are interested, check it out:

https://www.amazon.de/gp/aw/d/B09V5M8FR5/ref=tmm_kin_swatch_0?ie=UTF8&qid=&sr=

**Comment by Robinlovelace** [comment]
Hi Jannes, sounds good and thanks for the update. Coincidentally, I've started taking more structured notes recently with the amazing open source software LogSeq. I've seen lots of mention of Zettelkasten in the LogSeq community but never really figured out what it is! Will take a read of this and see if it can improve my note-taking game: https://discuss.logseq.com/t/my-zettelkasten-workflow-from-start-to-finish/8918

**Comment by jannes-m** [comment]
Ah, interesting, thanks! Never heard of logseq, will also have a look. Only tried a little bit Obsidian, but still stick with Notion despite some notable shortcomings, mostly due to the availability of the Android app so that I can put down my notes on the go and during the night.

**Comment by Robinlovelace** [comment]
LogSeq for Android + Laptop + Desktop + Syncthing = :star_struck:

**Comment by jannes-m** [comment]
Had a look at logseq, really interesting but I don't need an outliner tool. For what it's worth I am sharing my expectations for my all-in-one workspace (which is why I will switch from Notion to Obsidian):

- support **backlinking** (must have).
- sync automatically across devices (must have)
- come with **shortcuts** and a **command palette** (must have).
- have a **mobile app,** (a browser) and a Desktop app version (must have).
- support a hierarchical folder structure, e.g., for the different type of notes (fleeting, permanent and project notes). Additionally, a non-structured, bottom-up approach is supported with a graph view and fast searching options.
- be **publishable** (compiled HTML output) and the content should be editable (really nice to have)
- support multi-tagging (nice to have). When using tags as a surrogate for an index﻿, they are a must-have.
- be built on (local) Markdown files (really nice to have).
- support bibtex for citing purposes (really nice to have).
- support offline access
- be able to evaluate code chunks (nice to have).
- support vim key bindings (nice to have).
- should allow note-taking as well as organizing to dos and journaling (all-in one workspace, nice to have)
- be free and open source (nice to have).
- be easy to share (nice to have).

**Comment by Robinlovelace** [comment]
I think LogSeq does most of those pretty well. But there may well be better tools for your needs. Hopefully whichever tool it is can help with Geocomputation with R ; )

**Comment by jannes-m** [comment]
It sure will, no worries 😊

**Comment by jannes-m** [comment]
FYI @pat-s, little discussion on expectations regarding productivity tools  (Notion, Obsidian, logseq).

**Comment by jannes-m** [comment]
And @Robinlovelace maybe also interesting for you: I am using the android app mgit with ssh to sync my notes via github also on my mobile phone.

**Comment by pat-s** [comment]
Interesting discussion, thanks! I have already put so much content into Notion and it's doing a good job for what I want to do. Great to see additional note taking/notebook tools skyrocketing in the last years, this is a win for everyone!

**Comment by Robinlovelace** [comment]
> And @Robinlovelace maybe also interesting for you: I am using the android app mgit with ssh to sync my notes via github also on my mobile phone.

Sounds pretty complicated, what's wrong with Syncthing? Works for me.

**Comment by jannes-m** [comment]
Nothing wrong with syncthing. Still, I am preferring the git approach for now because:

- syncthing expects your devices to be on the same wifi. This will not work for me since we have an additional wifi for mobile devices at work.
- I am using git(hub) anyways for my notes

And I have read but not tested myself that 

- syncthing is draining fast your mobile's battery
- there might be difficult to solve merge conflicts when used with Obsidian

**Comment by Robinlovelace** [comment]
> syncthing expects your devices to be on the same wifi. This will not work for me since we have an additional wifi for mobile devices at work.

Don't think so, it works regardless of where your phone is, as long as it's online it works.

Yeah Syncthing does use up battery when on, turning it on when needed is my solution. Good to have an impromptu conversation about this, slightly off topic compared with the original post but interesting. Key thing: that these tools save more time than they take to get set-up, sounds like you've got a great set-up.

**Comment by Robinlovelace** [comment]
This is now fixed and the chapter is looking great: https://geocompr.robinlovelace.net/gis.html
