### ISSUE TITLE
Chapter 2 - Suggestion - Confusing Comment

### ISSUE THREAD

**Issue by Sreenath1986** [Robinlovelace/geocompr#890]
To begin with, I am a total newbie to geocomputation So please excuse me if my comment doesn't make sense.
Also, thank you so much for this wonderful book.

In Chapter 2 "2.2.1 An introduction to simple features", it shows that `summary(world["lifeExp"])` outputs a report on the geometry as well, leading to the conclusion "_This demonstrates the ‘sticky’ behavior of the geometry columns of sf objects, meaning the geometry is kept unless the user deliberately removes them_".

However, if we try the same summary approach in another common way `summary(world$lifeExp)`, it outputs report just on 'lifeExp' field, without the geometry info.

I am wondering whether this output contradicts the above conclusion of 'sticky behavior of geometry column of sf objects'.

Keen to know other's thoughts on the same. Thanks

**Comment by jannes-m** [comment]
The geometry column is sticky when you work on a dataframe, i.e., if you select an attribute column, the geometry column will automatically also be returned which makes perfect sense since otherwise the output dataframe would no longer be an sf object. The dollar operator on the other hand returns a single vector. So as usual what to use depends on what you would like to achieve.

**Comment by Robinlovelace** [comment]
Suggested further reading: https://adv-r.hadley.nz/vectors-chap.html#safe-subsetting
